"""Generate data/QUALITY.md — a completeness / quality report over the data spine.

Informational (not a CI gate): per-dataset row counts and per-column fill rates,
plus focused coverage tables for the things that matter to the book-companion
rigor work — page-level source citations (source_page), English labels (name_en),
Wikidata reconciliation, and the epistemic/certainty mix. Regenerate with:

    python tools/data_quality.py        # (also run by tools/build_all.py)
"""
import csv, os, sys, datetime
sys.stdout.reconfigure(encoding='utf-8')
sys.stderr.reconfigure(encoding='utf-8')
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, 'data')

# Canonical dataset order (FK parents first); editions/citations/etc. follow.
DATASETS = ['sources', 'places', 'itinerary', 'people', 'editions', 'citations',
            'trade', 'fragments', 'calendar', 'legs', 'events', 'edges']

def rd(name):
    with open(os.path.join(DATA, name + '.csv'), encoding='utf-8') as fh:
        return list(csv.DictReader(fh))

def filled(rows, col):
    return sum(1 for r in rows if (r.get(col) or '').strip())

def pct(n, d):
    return (100.0 * n / d) if d else 0.0

data = {ds: rd(ds) for ds in DATASETS}
out = []
w = out.append

w('# Data quality & completeness report')
w('')
w('> Generated by [`tools/data_quality.py`](../tools/data_quality.py) — informational, regenerated by `tools/build_all.py`. '
  'Counts reflect non-empty cells; this is a map of where the spine is complete and where rigor work (esp. page-level citations) remains.')
w('')
w(f'**Datasets:** {len(DATASETS)} · **Total rows:** {sum(len(r) for r in data.values())} · '
  f'**Generated:** {datetime.date.today().isoformat()}')
w('')

# ---- Per-dataset completeness ----
w('## Per-dataset completeness')
w('')
w('| Dataset | Rows | Cols | Fully populated | Sparse columns (fill %) |')
w('|---|--:|--:|--:|---|')
for ds in DATASETS:
    rows = data[ds]
    cols = list(rows[0].keys()) if rows else []
    full, sparse = [], []
    for c in cols:
        f = filled(rows, c)
        if f == len(rows):
            full.append(c)
        else:
            sparse.append(f'`{c}` {pct(f, len(rows)):.0f}%')
    sp = ', '.join(sparse) if sparse else '—'
    w(f'| {ds} | {len(rows)} | {len(cols)} | {len(full)}/{len(cols)} | {sp} |')
w('')

# ---- source_page coverage (the rigor target) ----
w('## Page-level source citations (`source_page`)')
w('')
w('The book-companion priority: link each fact to a page/folio in Khrustalev 2026. '
  'Coverage today (rows with a non-empty `source_page`):')
w('')
w('| Dataset | With `source_page` | Coverage |')
w('|---|--:|--:|')
total_sp = total_sp_rows = 0
for ds in DATASETS:
    rows = data[ds]
    if not rows or 'source_page' not in rows[0]:
        continue
    f = filled(rows, 'source_page')
    total_sp += f
    total_sp_rows += len(rows)
    w(f'| {ds} | {f}/{len(rows)} | {pct(f, len(rows)):.0f}% |')
w(f'| **total** | **{total_sp}/{total_sp_rows}** | **{pct(total_sp, total_sp_rows):.0f}%** |')
w('')

# ---- English labels ----
w('## English labels (`name_en`)')
w('')
w('| Dataset | With `name_en` | Coverage |')
w('|---|--:|--:|')
for ds in DATASETS:
    rows = data[ds]
    if rows and 'name_en' in rows[0]:
        f = filled(rows, 'name_en')
        w(f'| {ds} | {f}/{len(rows)} | {pct(f, len(rows)):.0f}% |')
w('')

# ---- Reconciliation + epistemic mix ----
w('## Reconciliation & epistemic mix')
w('')
for ds in ('places', 'people'):
    rows = data[ds]
    conf = sum(1 for r in rows if r.get('recon_status') == 'confirmed')
    wd = filled(rows, 'wikidata_qid')
    w(f'- **{ds}**: {conf}/{len(rows)} confirmed · {wd}/{len(rows)} linked to Wikidata')
epi = {}
for ds in DATASETS:
    for r in data[ds]:
        e = (r.get('epistemic') or '').strip()
        if e:
            epi[e] = epi.get(e, 0) + 1
w('')
w('Epistemic mix across all labelled rows: ' +
  ', '.join(f'{k} {v}' for k, v in sorted(epi.items(), key=lambda kv: -kv[1])) +
  f' (of {sum(epi.values())}).')
w('')

text = '\n'.join(out) + '\n'
with open(os.path.join(DATA, 'QUALITY.md'), 'w', encoding='utf-8', newline='') as fh:
    fh.write(text)
print(f'wrote data/QUALITY.md — {len(DATASETS)} datasets, source_page {total_sp}/{total_sp_rows} ({pct(total_sp, total_sp_rows):.0f}%)')
