"""Phase 2 — reconcile places & people to Wikidata (with verification), and pull
GeoNames (P1566) / Pleiades (P1584) / VIAF (P214) IDs from the matched item.

Places are verified by COORDINATE DISTANCE and must be a settlement (by type or
population), excluding racetracks/districts; people by instance-of=human (Q5) + a
description keyword check. A wrong QID is worse than a blank one, so IDs are written
ONLY for `confirmed` rows; `candidate`/`none` are left blank and listed in
data/reconciliation.md for human OpenRefine review.

Usage:  python tools/reconcile.py            # writes enriched CSVs + report
        python tools/reconcile.py --dry-run  # report only, do not touch CSVs
"""
import sys, os, json, time, csv, math, urllib.parse, urllib.request, urllib.error

sys.stdout.reconfigure(encoding="utf-8")
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
API = "https://www.wikidata.org/w/api.php"
UA = {"User-Agent": "AfanasiyNikitinAtlas/0.1 (https://github.com/gasyoun/AfanasiyNikitin; reconcile)"}
DRY = "--dry-run" in sys.argv
TOL_KM = 80.0
# settlement-ish instance-of (P31) classes
SETTLEMENT = {"Q486972", "Q515", "Q3957", "Q532", "Q5119", "Q15284", "Q1549591",
              "Q188509", "Q702492", "Q123705", "Q748149", "Q1637706", "Q15078955"}
# never accept these as a place match even if near
EXCLUDE = {"Q1777138", "Q27031206", "Q1149652", "Q1066984", "Q12813115"}  # racetrack, motorsport circuit, district of India, ...
SKIP_PLACE = {"somalia_coast", "balaklava_gurzuf", "mazandaran_sari"}  # regions/coasts: not point-reconcilable
# Human-reviewed picks the auto-matcher could not resolve (chosen among its own verified candidates):
PLACE_OVERRIDE = {"hormuz": "Q888643", "kaffa": "Q2585920", "gulbarga": "Q37112"}
PERSON_OVERRIDE = {"af": "Q48624", "sultan": "Q4519937", "farrukhyasar": "Q2002210"}


def api(params):
    params = dict(params); params["format"] = "json"
    req = urllib.request.Request(API + "?" + urllib.parse.urlencode(params), headers=UA)
    for attempt in range(6):
        try:
            with urllib.request.urlopen(req, timeout=30) as r:
                return json.load(r)
        except urllib.error.HTTPError as e:
            if e.code == 429:  # rate limited — honor Retry-After, then back off
                wait = int(e.headers.get("Retry-After", 0)) or 12 * (attempt + 1)
                time.sleep(wait); continue
            if attempt == 5:
                raise
            time.sleep(3)
        except Exception:
            if attempt == 5:
                raise
            time.sleep(3)
    return {}


def search(term, lang):
    d = api({"action": "wbsearchentities", "search": term, "language": lang,
             "uselang": lang, "limit": 12, "type": "item"})
    time.sleep(0.3)
    return [h["id"] for h in d.get("search", [])]


def entities(ids):
    out = {}
    ids = list(dict.fromkeys(ids))
    for i in range(0, len(ids), 50):
        d = api({"action": "wbgetentities", "ids": "|".join(ids[i:i + 50]),
                 "props": "claims|labels|descriptions", "languages": "en|ru"})
        out.update(d.get("entities", {}))
        time.sleep(0.3)
    return out


def vals(ent, prop):
    return [c.get("mainsnak", {}).get("datavalue", {}).get("value")
            for c in ent.get("claims", {}).get(prop, [])
            if c.get("mainsnak", {}).get("datavalue")]


def coord(ent):
    for v in vals(ent, "P625"):
        if isinstance(v, dict) and "latitude" in v:
            return (v["latitude"], v["longitude"])
    return None


def p31(ent):
    return {v["id"] for v in vals(ent, "P31") if isinstance(v, dict) and "id" in v}


def first_str(ent, prop):
    for v in vals(ent, prop):
        if isinstance(v, str):
            return v
    return ""


def label(ent):
    L = ent.get("labels", {})
    return (L.get("en") or L.get("ru") or {}).get("value", "")


def desc(ent):
    D = ent.get("descriptions", {})
    return " / ".join(d.get("value", "") for d in (D.get("en"), D.get("ru")) if d)


def haversine(a, b):
    R = 6371.0
    la1, lo1, la2, lo2 = map(math.radians, [a[0], a[1], b[0], b[1]])
    h = math.sin((la2 - la1) / 2) ** 2 + math.cos(la1) * math.cos(la2) * math.sin((lo2 - lo1) / 2) ** 2
    return 2 * R * math.asin(math.sqrt(h))


def read_csv(name):
    with open(os.path.join(ROOT, "data", name), encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    fields = [c for c in rows[0].keys() if c != "recon_status"] + ["recon_status"]
    return rows, fields


def write_csv(name, rows, fields):
    if DRY:
        return
    with open(os.path.join(ROOT, "data", name), "w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        w.writerows(rows)


report = ["# Phase 2 reconciliation report", "",
          "Generated by `tools/reconcile.py`. Places verified by coordinate distance "
          f"(tolerance {TOL_KM:.0f} km) and must be a settlement (by type or population). "
          "People verified by instance-of=human + description keyword. **IDs are written only "
          "for `confirmed` rows**; `candidate`/`none` are left blank for human review (OpenRefine → Wikidata).", ""]
open_items = []  # (kind, id, status, what's-needed) for the dedicated review list

# ---------- PLACES ----------
places, pfields = read_csv("places.csv")
report += ["## Places", "", "| place | QID | label | dist km | geonames | pleiades | status | note |",
           "|---|---|---|--:|---|---|---|---|"]
for r in places:
    pid, lat, lon = r["place_id"], float(r["lat"]), float(r["lon"])
    qid = gid = plid = lbl = note = ""
    dist = ""
    status = "none"
    if pid in SKIP_PLACE:
        status, note = "skip-region", "region/coast — not point-reconcilable"
    elif pid in PLACE_OVERRIDE:
        e = entities([PLACE_OVERRIDE[pid]]).get(PLACE_OVERRIDE[pid], {})
        c = coord(e)
        d = haversine((lat, lon), c) if c else None
        qid, lbl = PLACE_OVERRIDE[pid], label(e)
        gid, plid = first_str(e, "P1566"), first_str(e, "P1584")
        dist = f"{d:.1f}" if d is not None else ""
        status, note = "confirmed", "manual override (human-reviewed)"
    else:
        cands = []
        for term in dict.fromkeys([r["name_ru"], r["name_modern"].split(",")[0].strip(), pid.replace("_", " ")]):
            if term:
                cands += search(term, "en") + search(term, "ru")
        ents = entities(cands)
        scored = []
        for q, e in ents.items():
            c = coord(e)
            if not c:
                continue
            d = haversine((lat, lon), c)
            is_set = bool(p31(e) & SETTLEMENT)
            qualifies = (is_set or vals(e, "P1082")) and not (p31(e) & EXCLUDE)
            scored.append((d, is_set, qualifies, q, e))
        scored.sort(key=lambda t: t[0])
        good = [t for t in scored if t[2] and t[0] <= TOL_KM]
        good.sort(key=lambda t: (not t[1], t[0]))  # settlement-typed first, then nearest
        if good:
            d, _, _, q, e = good[0]
            qid, lbl, dist = q, label(e), f"{d:.1f}"
            gid, plid = first_str(e, "P1566"), first_str(e, "P1584")
            status = "confirmed"
        else:
            status = "candidate" if scored else "none"
            note = "no settlement within tol; nearest: " + \
                   ", ".join(f"{t[3]}={label(t[4])}({t[0]:.0f}km)" for t in scored[:3])
    if status == "confirmed":
        r["wikidata_qid"], r["geonames_id"], r["pleiades_id"] = qid, gid, plid
    else:
        r["wikidata_qid"] = r["geonames_id"] = r["pleiades_id"] = ""
    r["recon_status"] = status
    report.append(f"| {pid} | {qid} | {lbl} | {dist} | {gid} | {plid} | {status} | {note} |")
    if status in ("candidate", "none"):
        open_items.append(("place", pid, status, note or "no match"))
write_csv("places.csv", places, pfields)

# ---------- PEOPLE ----------
people, fields = read_csv("people.csv")
HINTS = {
    "af": ["nikitin", "никитин", "afanasy", "afanasiy", "афанасий"],
    "mikhail": ["tver", "тверь", "тверско"],
    "genadiy": ["bishop", "архиеп", "епископ", "tver"],
    "farrukhyasar": ["shirvan", "ширван"],
    "mahmud": ["bahmani", "gawan", "gilan", "бахман", "гаван", "vizier"],
    "sultan": ["bahmani", "бахман"],
    "mamyrev": ["dyak", "дьяк", "mamyrev", "мамырев"],
    "karamzin": ["historian", "writer", "карамзин", "историограф"],
}
report += ["", "## People", "", "| person | QID | label | VIAF | status | note |",
           "|---|---|---|---|---|---|"]
for r in people:
    pid = r["person_id"]
    qid = viaf = lbl = note = ""
    status = "none"
    if pid in PERSON_OVERRIDE:
        e = entities([PERSON_OVERRIDE[pid]]).get(PERSON_OVERRIDE[pid], {})
        qid, lbl, viaf = PERSON_OVERRIDE[pid], label(e), first_str(e, "P214")
        status, note = "confirmed", "manual override (human-reviewed)"
    elif r["relation"] == "self" or pid in HINTS:
        cands = []
        for t in [r["name_translit"], r["name_ru"]]:
            if t:
                cands += search(t, "en") + search(t, "ru")
        ents = entities(cands)
        humans = [(q, e) for q, e in ents.items() if "Q5" in p31(e)]
        hints = HINTS.get(pid, ["nikitin", "никитин", "afanasy"])
        matched = [(q, e) for q, e in humans
                   if any(h in (desc(e).lower() + " " + label(e).lower()) for h in hints)]
        # dedupe by QID, keep order
        seen = set(); matched = [(q, e) for q, e in matched if not (q in seen or seen.add(q))]
        if len(matched) == 1:
            q, e = matched[0]
            qid, lbl, viaf, status = q, label(e), first_str(e, "P214"), "confirmed"
        elif len(matched) > 1:
            status, note = "candidate", "multiple hint matches: " + ", ".join(f"{q}={label(e)}" for q, e in matched[:3])
        elif humans:
            status, note = "candidate", "human candidates, no hint match: " + ", ".join(f"{q}={label(e)}" for q, e in humans[:3])
        else:
            status, note = "none", "no human candidate"
    else:
        status, note = "collective", "collective/group — no individual authority record"
    if pid == "sultan":
        note = (note + "; " if note else "") + "the 1469-72 Bahmani sultan was Muhammad Shah III Lashkari — verify before assigning"
    if status == "confirmed":
        r["wikidata_qid"], r["viaf_id"] = qid, viaf
    else:
        r["wikidata_qid"] = r["viaf_id"] = ""
    r["recon_status"] = status
    report.append(f"| {pid} | {qid} | {lbl} | {viaf} | {status} | {note} |")
    if status in ("candidate", "none"):
        open_items.append(("person", pid, status, note or "no match"))
write_csv("people.csv", people, fields)

report += ["", "## Open items — need human review", "",
           f"{len(open_items)} entities left unreconciled (excluding collectives and skip-regions, "
           "which have no individual/point authority record by design).", "",
           "| kind | id | status | what's needed |", "|---|---|---|---|"]
for kind, i, st, nt in open_items:
    report.append(f"| {kind} | {i} | {st} | {nt} |")

summary = {}
for r in places + people:
    summary[r["recon_status"]] = summary.get(r["recon_status"], 0) + 1
report += ["", "## Summary", "", "```", json.dumps(summary, ensure_ascii=False, indent=2), "```",
           "", "Re-run after manual review: `python tools/reconcile.py`. "
           "To accept a candidate, set its `wikidata_qid` (and ids) in the CSV by hand."]

text = "\n".join(report)
print(text)
if not DRY:
    with open(os.path.join(ROOT, "data", "reconciliation.md"), "w", encoding="utf-8") as f:
        f.write(text + "\n")
    print("\n[written] data/places.csv, data/people.csv, data/reconciliation.md")
else:
    print("\n[dry-run] no files written")
